# Повторяю/Закрепляю numpy по книге

In [1]:
import numpy as np

In [3]:
np.__version__

'1.16.4'

In [6]:
np?

In [24]:
L1 = list(range(5))
L1

[0, 1, 2, 3, 4]

In [25]:
L2 = [str(c) for c in L1]

In [26]:
L2

['0', '1', '2', '3', '4']

Массивы с фиксированным типом в Python

In [27]:
import array

In [40]:
L = list(range(5))
A = array.array('i', L) #i - указывает на тип данных в массиве
A

array('i', [0, 1, 2, 3, 4])

Создание numpy-массивов

In [42]:
a = np.array([34,525,234])
a

array([ 34, 525, 234])

In [135]:
a = np.array([34,525,234], dtype='float') #задаем тип данных при помощи атрибута dtype
a

array([ 34., 525., 234.])

In [136]:
type(a[0])

numpy.float64

Создание numpy-массивов с нуля

In [58]:
#массив целых чисел длины 10, заполненный нулями
a = np.zeros(10, dtype='int')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
a = np.zeros([2,10], dtype='int') #двумерный массив целых чисел длины 10, заполненный нулями
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Массив размером 3х5 с единичными значениями плавающей точки

In [66]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 10, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Массив из 6 значений, равномерно распологающихся между 0 и 1

In [76]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

Массив 3х3 из случайных чисел от 0 до 1

In [94]:
np.random.random((3,3))

array([[0.42589919, 0.08673214, 0.61648217],
       [0.98429757, 0.66697757, 0.30544049],
       [0.09371826, 0.23541119, 0.41923992]])

In [95]:
5 * np.random.random((3,3)) -5

array([[-2.05177533, -0.69121319, -3.6899672 ],
       [-3.08166627, -3.86407885, -3.78093998],
       [-4.94201691, -1.78679631, -1.99138436]])

Массив размером 3х15 нормально распределенных случайных значения со средним 100 и стандартным отклонением 5

In [131]:
np.random.normal(100, 5, (3,15))

array([[101.24582823,  95.61020425, 102.47973656,  95.09311788,
        101.1883729 , 106.43834265, 100.76123898,  94.39746342,
         96.58694296, 109.12915798,  94.26350653, 104.08141352,
        107.78271821,  91.923349  ,  98.66677515],
       [ 98.41319579,  95.65159172, 107.71509512, 105.21208006,
         96.17625242, 108.78839347,  93.64513458, 108.74463739,
        102.26191849, 104.21636416,  99.28514891, 106.33556939,
         96.38739548, 111.27407566, 108.53082546],
       [102.62165298, 101.95903426,  94.49070536,  94.30016541,
         94.68536427, 102.79562953, 101.29827226, 103.48784171,
         97.91936214, 105.44648419, 102.11403614, 100.78683981,
        101.37652552,  94.44382634,  98.20937331]])

Массив 3х3 случайных целых числа в промежутке <b>[0,10)</b> <-- см. скобки

In [132]:
np.random.randint(0,10, (3,3))

array([[9, 8, 4],
       [5, 5, 2],
       [3, 2, 1]])

Создание единичной матрицы (identity matrix)

In [133]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])